// Generated by bindee 2.0 from immutable.hh.
#ifndef BIND_IMMUTABLE_HH
#define BIND_IMMUTABLE_HH

#include <pybind11/pybind11.h>
namespace py = pybind11;

@INCLUDES@

// Bind functions.

void bind_immutable_globals(py::module &bindee) {
    bindee.def("aa", (void (*)(const int *)) &aa);
    bindee.def("bb", (void (*)(const float *)) &bb);
    bindee.def("cc", (void (*)(const double *)) &cc);
    bindee.def("dd", (void (*)(const long &)) &dd);
    bindee.def("ee", (void (*)(const bool &)) &ee);
    bindee.def("ff", (void (*)(const std::string *)) &ff);
    bindee.def("gg", (void (*)(const std::string &)) &gg);
    bindee.def("aaa", (void (*)(int)) &aaa);
    bindee.def("bbb", (void (*)(float)) &bbb);
    bindee.def("ccc", (void (*)(double)) &ccc);
    bindee.def("ddd", (void (*)(long)) &ddd);
    bindee.def("eee", (void (*)(bool)) &eee);
    bindee.def("fff", (void (*)(std::string)) &fff);
}

#endif // BIND_IMMUTABLE_HH
