// Generated by bindee 2.0 from with_chain.hh.
#ifndef BIND_WITH_CHAIN_HH
#define BIND_WITH_CHAIN_HH

#include <pybind11/pybind11.h>
namespace py = pybind11;

@INCLUDES@

// Records.

template <typename Target>
void bind_A(Target &target);

// Bind functions.

template <typename Target>
void bind_A(Target &target) {
    using Class = A;

    std::string className = "A";
    std::string docString = @DOC_STRING@;

    py::class_<Class>(target, className.c_str(), docString.c_str())
        .def_readwrite("x", &Class::x)
        .def_readwrite("y", &Class::y)
        .def_readwrite("z", &Class::z)
    ;
}

#endif // BIND_WITH_CHAIN_HH
