// Generated by bindee 2.1 from inner_record.hh.
#ifndef BIND_INNER_RECORD_HH
#define BIND_INNER_RECORD_HH

#include <pybind11/pybind11.h>
namespace py = pybind11;

@INCLUDES@

// Records.

template <typename Target>
void bind_A(Target &target);
template <typename Target>
void bind__B(Target &target);

// Bind functions.

template <typename Target>
void bind_A(Target &target) {
    using Class = A;

    std::string className = "A";
    std::string docString = @DOC_STRING@;

    py::class_<Class> bindee(target, className.c_str(), docString.c_str());
}

template <typename Target>
void bind__B(Target &target) {
    using Class = A::_B;

    std::string className = "_B";
    std::string docString = @DOC_STRING@;

    py::class_<Class> bindee(target, className.c_str(), docString.c_str());
}

#endif // BIND_INNER_RECORD_HH
