// Generated by bindee 2.1 from write_only_prop.hh.
#ifndef BIND_WRITE_ONLY_PROP_HH
#define BIND_WRITE_ONLY_PROP_HH

#include <pybind11/pybind11.h>
namespace py = pybind11;

@INCLUDES@

// Records.

template <typename Target>
void bind_Example(Target &target);

// Bind functions.

template <typename Target>
void bind_Example(Target &target) {
    using Class = Example;

    std::string className = "Example";
    std::string docString = @DOC_STRING@;

    py::class_<Class> bindee(target, className.c_str(), docString.c_str());
    bindee.def_property("z", nullptr, (void (Class::*)(int)) &Class::setZ);
    bindee.def_property("x", nullptr, (void (Class::*)(int)) &Class::setX);
}

#endif // BIND_WRITE_ONLY_PROP_HH
